export { default as About } from './About.jsx'
export { default as Buy } from './Buy.jsx'
export { default as Home } from './Home.jsx'
export { default as Contact } from './Contact.jsx'
export { default as Login } from './Login.jsx'
export { default as Addproducts } from './Addproducts.jsx'